// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALk29NFllghz-9nKTsjhLf5Hyi2_TjI_o',
    appId: '1:1079354918065:web:22fac8080338dda71a4e90',
    messagingSenderId: '1079354918065',
    projectId: 'food-app-mh',
    authDomain: 'food-app-mh.firebaseapp.com',
    storageBucket: 'food-app-mh.firebasestorage.app',
    measurementId: 'G-S15ZMVDZS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3IqzXycjIlXjE-wkj1CVnXwhjN1QnGHw',
    appId: '1:1079354918065:android:53dec832210880691a4e90',
    messagingSenderId: '1079354918065',
    projectId: 'food-app-mh',
    storageBucket: 'food-app-mh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBnIsryYbQQfEQU_7fpYsYEJ43VkEuvKk',
    appId: '1:1079354918065:ios:aca3b16d04696afa1a4e90',
    messagingSenderId: '1079354918065',
    projectId: 'food-app-mh',
    storageBucket: 'food-app-mh.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBnIsryYbQQfEQU_7fpYsYEJ43VkEuvKk',
    appId: '1:1079354918065:ios:aca3b16d04696afa1a4e90',
    messagingSenderId: '1079354918065',
    projectId: 'food-app-mh',
    storageBucket: 'food-app-mh.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALk29NFllghz-9nKTsjhLf5Hyi2_TjI_o',
    appId: '1:1079354918065:web:a14513be629327e61a4e90',
    messagingSenderId: '1079354918065',
    projectId: 'food-app-mh',
    authDomain: 'food-app-mh.firebaseapp.com',
    storageBucket: 'food-app-mh.firebasestorage.app',
    measurementId: 'G-FW1GDDWD98',
  );
}
